-- Official U.S. adult component portions, checked 2026-09-27.
-- Source date is intentionally NULL: filename and footer provide differing months.
-- Taco tortilla fiber is <1 g in source; retained as unknown, never fabricated.
-- Chips values are for the whole 4 oz order, not one half of that order.
begin;
insert into public.foods (name,brand,source,source_id,source_url,source_release,source_data_type,serving_grams,serving_amount,serving_unit,portions,nutrient_values,calories,protein_g,carbs_g,fat_g,fiber_g,sugar_g,saturated_fat_g,sodium_mg) values
('Flour Tortilla (burrito)','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-flour-tortilla-burrito','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "1 tortilla", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',320,8,50,9,3,0,0.5,600),
('Flour Tortilla (taco)','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-flour-tortilla-taco','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "1 tortilla", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',80,2,13,2.5,null,0,0,160),
('Crispy Corn Tortilla','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-crispy-corn-tortilla','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "1 tortilla", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',70,1,10,3,1,0,0,0),
('Cilantro-Lime Brown Rice','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-cilantro-lime-brown-rice','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',210,4,36,6,2,0,0,190),
('Cilantro-Lime White Rice','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-cilantro-lime-white-rice','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',210,4,40,4,1,0,1,350),
('Black Beans','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-black-beans','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',130,8,22,1.5,7,2,0,210),
('Pinto Beans','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-pinto-beans','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',130,8,21,1.5,8,1,0,210),
('Fajita Vegetables','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-fajita-vegetables','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "2 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',20,1,5,0,1,2,0,150),
('Barbacoa','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-barbacoa','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 65, "1257": 0}',170,24,2,7,1,0,2.5,530),
('Chicken','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-chicken','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 125, "1257": 0}',180,32,0,7,0,0,3,310),
('Carnitas','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-carnitas','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 65, "1257": 0}',210,23,0,12,0,0,7,450),
('Steak','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-steak','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 80, "1257": 0}',150,21,1,6,1,0,2.5,330),
('Sofritas','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-sofritas','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',150,8,9,10,3,5,1.5,560),
('Fresh Tomato Salsa','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-fresh-tomato-salsa','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',25,0,4,0,1,1,0,550),
('Roasted Chili-Corn Salsa','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-roasted-chili-corn-salsa','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',80,3,16,1.5,3,4,0,330),
('Tomatillo-Green Chili Salsa','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-tomatillo-green-chili-salsa','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "2 fl oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',15,0,4,0,0,2,0,260),
('Tomatillo-Red Chili Salsa','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-tomatillo-red-chili-salsa','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "2 fl oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',30,0,4,0,1,0,0,500),
('Cheese','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-cheese','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "1 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 30, "1257": 0}',110,6,1,8,0,0,5,190),
('Sour Cream','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-sour-cream','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "2 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 40, "1257": 0}',110,2,2,9,0,2,7,30),
('Guacamole (topping/side)','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-guacamole-topping-side','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "4 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',230,2,8,22,6,1,3.5,370),
('Queso Blanco (entree)','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-queso-blanco-entree','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "2 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 30, "1257": 0}',120,5,4,9,0,1,6,250),
('Supergreens Salad Mix','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-supergreens-salad-mix','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "3 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',15,1,3,0,2,1,0,15),
('Romaine Lettuce (tacos)','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-romaine-lettuce-tacos','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "1 oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',5,0,1,0,1,0,0,0),
('Chips (regular)','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-chips-regular','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "one 4 oz order (guide: serves 2)", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',540,7,73,25,7,1,3.5,390),
('Chipotle-Honey Vinaigrette','Chipotle','Chipotle U.S. Nutrition Guide (3-2025 file; OCT-2024-US-CK)','chipotle-us-chipotle-honey-vinaigrette','https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf#page=2',null,'Restaurant menu',null,1,'serving','[{"label": "2 fl oz portion", "amount": 1, "unit": "serving"}]','{"1253": 0, "1257": 0}',220,1,18,16,1,12,2.5,850)
on conflict(source,source_id) where source_id is not null do update set
  name=excluded.name,
  brand=excluded.brand,
  source_url=excluded.source_url,
  source_release=excluded.source_release,
  source_data_type=excluded.source_data_type,
  serving_grams=excluded.serving_grams,
  serving_amount=excluded.serving_amount,
  serving_unit=excluded.serving_unit,
  portions=excluded.portions,
  nutrient_values=excluded.nutrient_values,
  calories=excluded.calories,
  protein_g=excluded.protein_g,
  carbs_g=excluded.carbs_g,
  fat_g=excluded.fat_g,
  fiber_g=excluded.fiber_g,
  sugar_g=excluded.sugar_g,
  saturated_fat_g=excluded.saturated_fat_g,
  sodium_mg=excluded.sodium_mg;
commit;
